# Generated by Django 6.0.4 on 2026-04-28 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.TextField(max_length=100)),
                ('name', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
                ('current_cycle_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cycle.cyclemodel')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
