# Generated by Django 6.0.4 on 2026-04-28 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='current_cycle_id',
            new_name='current_cycle',
        ),
    ]
