# Generated by Django 6.0.4 on 2026-05-02 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0001_initial'),
        ('login', '0002_rename_current_cycle_id_usermodel_current_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='current_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cycle.cyclemodel'),
        ),
    ]
