# Generated by Django 6.0.4 on 2026-04-27 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('log_date', models.DateField()),
                ('description', models.TextField()),
                ('note', models.TextField(null=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='transaction.categorymodel')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cycle.cyclemodel')),
            ],
            options={
                'db_table': 'Transaction',
            },
        ),
    ]
