# Generated by Django 6.0.4 on 2026-05-06 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='category',
            field=models.ForeignKey(db_column='category_name', default='General', on_delete=django.db.models.deletion.CASCADE, to='transaction.categorymodel'),
        ),
    ]
