# Generated by Django 6.0.4 on 2026-04-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.TextField(choices=[('EN', 'English'), ('AR', 'Arabic')])),
                ('currency', models.TextField(choices=[('$', 'Us Dollar'), ('EGP', 'Egyptian Pound')])),
                ('theme', models.TextField(choices=[('Light Mode', 'Light'), ('Dark Mode', 'Dark')])),
                ('cycle_duration', models.IntegerField()),
                ('budget_threshold', models.FloatField()),
            ],
        ),
    ]
