# Generated by Django 6.0.4 on 2026-05-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Specific Dates of the Month'), ('WEEKLY', 'Specific Days of the Week')], default='MONTHLY', max_length=10)),
                ('days_of_month', models.JSONField(blank=True, default=list, help_text='List of days in the month (1-31)', null=True)),
                ('days_of_week', models.JSONField(blank=True, default=list, help_text='List of day abbreviations', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
