# Generated by Django 6.0.4 on 2026-05-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicexpense',
            name='days_of_month',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='periodicexpense',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
