# Generated by Django 6.0.5 on 2026-05-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.TextField(choices=[('EN', 'English'), ('AR', 'Arabic')], default='EN')),
                ('currency', models.TextField(choices=[('$', 'Us Dollar'), ('EGP', 'Egyptian Pound')], default='$')),
                ('theme', models.TextField(choices=[('Light Mode', 'Light'), ('Dark Mode', 'Dark')], default='Light Mode')),
            ],
            options={
                'db_table': 'Settings',
            },
        ),
    ]
