# Generated by Django 6.0.5 on 2026-05-07 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CycleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('amount', models.FloatField()),
            ],
            options={
                'db_table': 'Cycle',
            },
        ),
        migrations.CreateModel(
            name='ActiveCycleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cycle.cyclemodel')),
            ],
            options={
                'db_table': 'active_cycle',
            },
        ),
    ]
