# Generated by Django 6.0.4 on 2026-04-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyclemodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
