# Generated by Django 6.0.4 on 2026-04-29 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0002_cyclemodel_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cyclemodel',
            name='is_active',
        ),
        migrations.CreateModel(
            name='ActiveCycleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cycle.cyclemodel')),
            ],
            options={
                'db_table': 'active_cycle',
            },
        ),
    ]
